### ISSUE TITLE
Error when extracting tables

### ISSUE THREAD

**Issue by Rajmehta123** [thibaultvt/Diard#10]
The layout detected table on pdf but when I enable table detection, it throws the following error.

```
Traceback (most recent call last):

  File "/var/folders/kt/7g6lg6l15s96drlgk_p123tc0000gp/T/ipykernel_81639/3626377987.py", line 2, in <module>
    doc.extract_layouts(visualize=True, segment_sections=True)

  File "/Users/rmehta/Diard/modules/document.py", line 361, in extract_layouts
    self.__set_extracted_data(b, img, page, j)

  File "/Users/rmehta/Diard/modules/document.py", line 262, in __set_extracted_data
    snippet, lang=self.lang, debug=False, threshold=0.7

  File "/Users/rmehta/Diard/modules/tables.py", line 420, in get_table_data
    objs = structure_table(objs, table_bbox)

  File "/Users/rmehta/Diard/modules/tables.py", line 142, in structure_table
    bottom_y = rows[-1]["bbox"][3]

IndexError: list index out of range
```

The pretrained model I used has been downloaded as given in instructions. `pubtables1m_detection_detr_r18.pth`

**Comment by baulbo** [comment]
@Rajmehta123 , as mentioned in the README introduction "(note: TE was not tested thoroughly and should be updated for serious use)". You should look at the official repository -> https://github.com/microsoft/table-transformer

**Comment by Rajmehta123** [comment]
I found the solution. The model file used is for detection, just replace the model file with structure and it should work.
